### ISSUE TITLE
ModuleNotFoundError: No module named 'params' 

### ISSUE THREAD

**Issue by prokopevaleksey** [GauravBh1010tt/DeepLearn#4]
used only once in `word_vecs = [[we[j][i] for j in range(params.embedding_size)] for i in range(len(words[0]))]`
in `load_embeds` function from ntn_input.py

**Comment by prokopevaleksey** [comment]
also `NameError: name 'aggregate' is not defined ` and I wasn't able to get what suppose to be there instead.

**Comment by GauravBh1010tt** [comment]
@prokopevaleksey - Updated the modules. Just follow the same instructions given on Readme page.
