### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'T'

### ISSUE THREAD

**Issue by basma-b** [GauravBh1010tt/DeepLearn#6]

**Comment by GauravBh1010tt** [comment]
@basma-b - Please make sure you have the correct system dependencies - 
https://github.com/GauravBh1010tt/DeepLearn/blob/master/requirements.txt
In my code, I have used Keras with theano backend, so make sure theano is properly configured with Keras.

**Comment by basma-b** [comment]
Thank you, solved my problem by changing keras backend to theano. Thank you !

**Comment by meghanagabhushan** [comment]
Changing Keras backend from tensorflow to theano is not working for me.
